// 데이터 삽입 스크립트 예시
const mongoose = require('mongoose');

// MongoDB 연결 설정
mongoose.connect('mongodb://admin:1234@10.10.0.102:30027/?directConnection=true');

// 로그 데이터 스키마 정의
const logDataSchema = new mongoose.Schema({
  date: String,
  source: String,
  destination: String,
  encryptionStatus: String,
  tlsVersion: String,
  cipherSuite: String,
  certSignatureAlgorithm: String,
  ellipticCurve: String,
  skeSignatureAlgorithm: String,
  tlsVersionVulnerability: Number,
  cipherSuiteVulnerability: Number,
  certSignatureAlgorithmVulnerability: Number,
  ellipticCurveVulnerability: Number,
  skeSignatureAlgorithmVulnerability: Number,
});

// MongoDB 모델 생성
const LogData = mongoose.model('LogData', logDataSchema);

// 예시 데이터
const logData = [
  {
    "date": "2024-07-16 18:19:11",
    "source": "google.com:443",
    "destination": "Pod/default/auth-58b557ffd8-zjxn7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "sha256WithRSAEncryption",
    "ellipticCurve": "x25519",
    "skeSignatureAlgorithm": "ecdsa_secp256r1_sha256",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:19:21",
    "source": "Pod/default/backend-585ddcb876-xlgk7",
    "destination": "Pod/default/auth-58b557ffd8-zjxn7",
    "encryptionStatus": "None",
    "tlsVersion": "",
    "cipherSuite": "",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 2,
    "cipherSuiteVulnerability": 2,
    "certSignatureAlgorithmVulnerability": 2,
    "ellipticCurveVulnerability": 2,
    "skeSignatureAlgorithmVulnerability": 2,
  },
  {
    "date": "2024-07-16 18:20:01",
    "source": "Pod/default/payment-548d5f7884-wjmn4",
    "destination": "Pod/default/backend-585ddcb876-xlgk7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:12",
    "source": "Pod/default/auth-58b557ffd8-zjxn7",
    "destination": "Pod/default/backend-585ddcb876-xlgk7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_AES_256_GCM_SHA384",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:21",
    "source": "Pod/default/backend-585ddcb876-xlgk7",
    "destination": "Pod/default/auth-58b557ffd8-zjxn7",
    "encryptionStatus": "None",
    "tlsVersion": "",
    "cipherSuite": "",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 2,
    "cipherSuiteVulnerability": 2,
    "certSignatureAlgorithmVulnerability": 2,
    "ellipticCurveVulnerability": 2,
    "skeSignatureAlgorithmVulnerability": 2,
  },
  {
    "date": "2024-07-16 18:20:27",
    "source": "Pod/default/backend-585ddcb876-xlgk7",
    "destination": "dankook.ac.kr",
    "encryptionStatus": "Insecure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
    "certSignatureAlgorithm": "sha384WithRSAEncryption",
    "ellipticCurve": "x25519",
    "skeSignatureAlgorithm": "ECDSA_P384_SHA384",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 1,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "portal.dankook.ac.kr",
    "destination": "Pod/default/auth-58b557ffd8-zjxn7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_AES_128_GCM_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/default/payment-548d5f7884-wjmn4",
    "destination": "naver.com",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/default/backend-585ddcb876-xlgk7",
    "destination": "google.com:443",
    "encryptionStatus": "None",
    "tlsVersion": "",
    "cipherSuite": "",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 2,
    "cipherSuiteVulnerability": 2,
    "certSignatureAlgorithmVulnerability": 2,
    "ellipticCurveVulnerability": 2,
    "skeSignatureAlgorithmVulnerability": 2,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/default/auth-58b557ffd8-zjxn7",
    "destination": "boanlab.com",
    "encryptionStatus": "Insecure",
    "tlsVersion": "TLS 1.1",
    "cipherSuite": "TLS_RSA_WITH_AES_128_GCM_SHA256",
    "certSignatureAlgorithm": "md5WithRSAEncryption",
    "ellipticCurve": "SECP521R1",
    "skeSignatureAlgorithm": "ECDSA_P521_SHA512",
    "tlsVersionVulnerability": 1,
    "cipherSuiteVulnerability": 1,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/istio-system/istiod-dd8c7bc6c-fc59f",
    "destination": "Pod/default/auth-58b557ffd8-zjxn7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_AES_256_GCM_SHA384",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/istio-system/istiod-dd8c7bc6c-fc59f",
    "destination": "Pod/default/backend-585ddcb876-xlgk7",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_AES_256_GCM_SHA384",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/istio-system/istiod-dd8c7bc6c-fc59f",
    "destination": "Pod/default/payment-548d5f7884-wjmn4",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_AES_256_GCM_SHA384",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/istio-system/istiod-dd8c7bc6c-fc59f",
    "destination": "Pod/test/testpod",
    "encryptionStatus": "None",
    "tlsVersion": "",
    "cipherSuite": "",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 2,
    "cipherSuiteVulnerability": 2,
    "certSignatureAlgorithmVulnerability": 2,
    "ellipticCurveVulnerability": 2,
    "skeSignatureAlgorithmVulnerability": 2,
  },
  {
    "date": "2024-07-16 18:20:29",
    "source": "Pod/calico-kube-controllers-7c968b5878-qtfj9",
    "destination": "Pod/kube-system/calico-node-25ccc",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "certSignatureAlgorithm": "md5WithRSAEncryption",
    "ellipticCurve": "X25519",
    "skeSignatureAlgorithm": "ECDSA_P256_SHA256",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:22",
    "source": "Pod/kube-system/calico-kube-controllers-7c968b5878-qtfj9",
    "destination": "Pod/kube-system/calico-node-rvmq5",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "certSignatureAlgorithm": "md2WithRSAEncryption",
    "ellipticCurve": "BP384R1",
    "skeSignatureAlgorithm": "RSA_PSS_SHA384",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:29",
    "source": "Pod/kube-system/calico-kube-controllers-7c968b5878-qtfj9",
    "destination": "Pod/kube-system/calico-node-vjm9p",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "certSignatureAlgorithm": "sha256WithRSAEncryption",
    "ellipticCurve": "SECP256K1",
    "skeSignatureAlgorithm": "RSA_PSS_SHA512",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:31",
    "source": "Pod/kube-system/coredns-67d9d866cc-nkvj5",
    "destination": "Pod/kube-system/calico-node-vjm9p",
    "encryptionStatus": "Insecure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
    "certSignatureAlgorithm": "sha256WithRSAEncryption",
    "ellipticCurve": "SECP256K1",
    "skeSignatureAlgorithm": "RSA_PSS_SHA512",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 1,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:32",
    "source": "Pod/kube-system/kube-apiserver-k8s-master",
    "destination": "Pod/kube-system/coredns-67d9d866cc-nkvj5",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.2",
    "cipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "certSignatureAlgorithm": "sha256WithRSAEncryption",
    "ellipticCurve": "BP384R1",
    "skeSignatureAlgorithm": "RSA_PSS_SHA512",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:33",
    "source": "Pod/kube-system/kube-proxy-5xmkn",
    "destination": "Pod/kube-system/kube-apiserver-k8s-master",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:34",
    "source": "Pod/kube-system/kube-proxy-mw667",
    "destination": "Pod/kube-system/kube-apiserver-k8s-master",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
  {
    "date": "2024-07-16 18:24:34",
    "source": "Pod/kube-system/kube-proxy-rlbbf",
    "destination": "Pod/kube-system/kube-apiserver-k8s-master",
    "encryptionStatus": "Secure",
    "tlsVersion": "TLS 1.3",
    "cipherSuite": "TLS_CHACHA20_POLY1305_SHA256",
    "certSignatureAlgorithm": "",
    "ellipticCurve": "",
    "skeSignatureAlgorithm": "",
    "tlsVersionVulnerability": 0,
    "cipherSuiteVulnerability": 0,
    "certSignatureAlgorithmVulnerability": 0,
    "ellipticCurveVulnerability": 0,
    "skeSignatureAlgorithmVulnerability": 0,
  },
];

// 로그 데이터 스키마 정의
const keyDataSchema = new mongoose.Schema({
  date: String,
  sans: String,
  ttl: String,
  client: String,
  status: String,
});

// MongoDB 모델 생성
const KeyData = mongoose.model('KeyData', keyDataSchema);

// 예시 데이터
const keyData = [
  {
    date: '2024-07-18 18:28:43',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/istio-system/istio-ingressgateway-76594f5654-zlddx.istio-system',
    status: 'Generating',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/auth-58b557ffd8-zjxn7',
    status: 'Generating',
  },
  {
    date: '2024-07-18 18:28:45',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/backend-585ddcb876-xlgk7',
    status: 'Generating',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/payment-548d5f7884-wjmn4',
    status: 'Generating',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/test/ubuntu-688958d5c9-ts5hf',
    status: 'Terminated',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/test/controller-c45f864fc-zm778',
    status: 'Terminated',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/test/solution-mr2rf',
    status: 'Terminated',
  },
  {
    date: '2024-07-18 18:28:44',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/payment-548d5f7884-wjmn4',
    status: 'Generating',
  },
  {
    date: '2024-07-18 18:28:45',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/istio-system/istio-ingressgateway-76594f5654-zlddx.istio-system',
    status: 'Signed',
  },
    {
    date: '2024-07-18 18:28:45',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/auth-58b557ffd8-zjxn7',
    status: 'Signed',
  },
  {
    date: '2024-07-18 18:28:49',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/backend-585ddcb876-xlgk7',
    status: 'Signed',
  },
  {
    date: '2024-07-18 18:28:49',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/payment-548d5f7884-wjmn4',
    status: 'Signed',
  },
  {
    date: '2024-07-18 18:28:50',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/payment-548d5f7884-wjmn4',
    status: 'Signed',
  },
  {
    date: '2024-07-18 18:28:51',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/backend-585ddcb876-xlgk7',
    status: 'Regenerating',
  },
  {
    date: '2024-07-18 18:28:51',
    sans: 'spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account',
    ttl: '12h0m0s',
    client: 'Pod/default/backend-585ddcb876-xlgk7',
    status: 'Signed',
  },
];

// 데이터 삽입 함수
async function insertData() {
  try {
    // logData 삽입
    const insertedLogData = await LogData.insertMany(logData);
    console.log('Inserted log data:', insertedLogData);

    // keyData 삽입
    const insertedKeyData = await KeyData.insertMany(keyData);
    console.log('Inserted key data:', insertedKeyData);
  } catch (error) {
    console.error('Error inserting data:', error);
  } finally {
    // 연결 종료
    mongoose.disconnect();
  }
}

// 데이터 삽입 실행
insertData();
